###
# GET All Contacts
GET http://localhost:3000/restaurants
Accept: application/json

###
# GET Contact by ID
GET http://localhost:3000/restaurants/692207b0b859b1b82bae5f5a
Accept: application/json

###
# POST Create New Contact
POST http://localhost:3000/restaurants
Content-Type: application/json

{
    "name": "",
    "cuisine": "Fusion",
    "location": "123 New St, Springfield",
    "rating": "hss"
}

###
# PUT Update Contact by ID
PUT http://localhost:3000/restaurants/692207b0b859b1b82bae5f5a
Content-Type: application/json
{
    "name": "Updated Restaurant",
    "cuisine": "Updated Cuisine",
    "location": "456 Updated St, Springfield",
    "rating": 4.5
}

###
# DELETE Contact by ID
DELETE http://localhost:3000/restaurants/6921effcecc30f1bf1de8d74